# Generated by Django 4.1 on 2022-08-31 08:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='responseUser',
            new_name='responseAuthor',
        ),
        migrations.AddField(
            model_name='notice',
            name='ck1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
