# Generated by Django 4.1 on 2022-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_notice_noticeauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='responseAdmission',
            field=models.BooleanField(default=False),
        ),
    ]
